# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2-m1xeImEGtxn7d6_n9OVEHlFHzuEd8
"""



from google.colab import drive
drive.mount('/content/drive')

# החלף את הנתיב הזה בנתיב המדויק לתיקייה שלך בתוך הדרייב
source_folder = '/content/drive/MyDrive/GarbageClassificitionDataSet1'
destination_folder = '/content/dataset'

# העתקת התיקייה מהדרייב לסביבה המקומית ב-Colab
!cp -r "{source_folder}" "{destination_folder}"

print("ההעתקה הסתיימה בהצלחה!")

# Commented out IPython magic to ensure Python compatibility.
# ==========================================
# תא 0: הגדרת סביבה, חיבור לדרייב ו-TensorBoard
# ==========================================
from google.colab import drive
import os



# הגדרת נתיב הגיבוי הקבוע בדרייב
BACKUP_DIR = '/content/drive/MyDrive/Trash_Classification_Backup'
os.makedirs(BACKUP_DIR, exist_ok=True)
print(f"✅ תיקיית הגיבוי בדרייב מוכנה: {BACKUP_DIR}")

# פתיחת חלון הגרפים
# %load_ext tensorboard
# %tensorboard --logdir runs

# ==========================================
# הכנת נתונים: פיצול ל-Train, Val, Test
# ==========================================
# התקנת הספריה הייעודית לפיצול תיקיות תמונה
!pip install split-folders
import splitfolders

# הנתיב שבו נמצאות כרגע התיקיות של המחלקות (התיקייה המקורית שלך)
input_folder = "/content/dataset"

# הנתיב החדש שייווצר ויכיל את החלוקה המסודרת שהמודל צריך
output_folder = "/content/split_dataset"

print("מתחיל בפיצול הנתונים...")

# ביצוע הפיצול ביחס של 70%-15%-15%
# seed=42 מבטיח שאם תריץ את הקוד שוב, החלוקה תישאר בדיוק אותה חלוקה (חשוב למחקר מדעי)
splitfolders.ratio(input_folder, output=output_folder, seed=42, ratio=(0.7, 0.15, 0.15))

print(f"✅ הפיצול הסתיים בהצלחה! הנתונים המוכנים מחכים בתיקייה: {output_folder}")

# Commented out IPython magic to ensure Python compatibility.
import os

# מוודא שהתיקייה קיימת גם אם האימון עדיין לא התחיל
os.makedirs('runs', exist_ok=True)

# סוגר בכוח תהליכי TensorBoard ישנים שנתקעו ברקע
!kill -9 $(ps -ef | grep tensorboard | awk '{print $2}') 2>/dev/null

# מפעיל את TensorBoard מחדש
# %reload_ext tensorboard
# %tensorboard --logdir runs

# ==========================================
# Run 1: Baseline Model (כולל חיבור מובנה לדרייב)
# ==========================================
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm
import os
import shutil
from google.colab import drive

# 1. חיבור לדרייב ויצירת תיקיית גיבוי (התיקון לשגיאה)
print("מוודא חיבור ל-Google Drive...")
drive.mount('/content/drive')
BACKUP_DIR = '/content/drive/MyDrive/Trash_Classification_Project_Backup'
os.makedirs(BACKUP_DIR, exist_ok=True)
print(f"תיקיית הגיבוי מוכנה בנתיב: {BACKUP_DIR}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
run_name = "Run1_Baseline"
writer = SummaryWriter(f'runs/{run_name}')

# 2. הגדרת היפר-פרמטרים בסיסיים
hparams = {
    'img_size': 224,
    'batch_size': 32,
    'epochs': 40,
    'optimizer': 'SGD',
    'learning_rate': 0.01,
    'weight_decay': 0.0,
    'augmentations': 'None'
}

# 3. הכנת נתונים - ללא אוגמנטציות
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
transform = transforms.Compose([
    transforms.Resize((hparams['img_size'], hparams['img_size'])),
    transforms.ToTensor(),
    normalize
])

# שימוש בנתיב המפוצל החדש שיצרנו
data_dir = "/content/split_dataset"
train_dataset = datasets.ImageFolder(os.path.join(data_dir, 'train'), transform=transform)
val_dataset = datasets.ImageFolder(os.path.join(data_dir, 'val'), transform=transform)
test_dataset = datasets.ImageFolder(os.path.join(data_dir, 'test'), transform=transform)

train_loader = DataLoader(train_dataset, batch_size=hparams['batch_size'], shuffle=True, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size=hparams['batch_size'], shuffle=False, num_workers=4)
test_loader = DataLoader(test_dataset, batch_size=hparams['batch_size'], shuffle=False, num_workers=4)

# 4. אתחול מודל מאפס
model = models.resnet50(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(train_dataset.classes))
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=hparams['learning_rate'])
best_val_acc = 0.0

# 5. לולאת אימון
for epoch in range(hparams['epochs']):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for inputs, labels in tqdm(train_loader, desc=f"Run 1 - Epoch {epoch+1}/{hparams['epochs']}"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    train_loss = running_loss / len(train_loader)
    train_acc = 100. * correct / total

    # שלב אימות
    model.eval()
    val_loss, val_correct, val_total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            _, predicted = outputs.max(1)
            val_total += labels.size(0)
            val_correct += predicted.eq(labels).sum().item()

    val_loss = val_loss / len(val_loader)
    val_acc = 100. * val_correct / val_total
    print(f"Epoch {epoch+1}/{hparams['epochs']} - Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")

    writer.add_scalars('Loss', {'Train': train_loss, 'Val': val_loss}, epoch)
    writer.add_scalars('Accuracy', {'Train': train_acc, 'Val': val_acc}, epoch)

    # שמירה לדרייב
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        save_path = os.path.join(BACKUP_DIR, f'{run_name}_best.pth')
        torch.save(model.state_dict(), save_path)

    shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)

# מבחן סופי
model.load_state_dict(torch.load(os.path.join(BACKUP_DIR, f'{run_name}_best.pth')))
model.eval()
test_correct, test_total = 0, 0
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = outputs.max(1)
        test_total += labels.size(0)
        test_correct += predicted.eq(labels).sum().item()

test_acc = 100. * test_correct / test_total
print(f"Run 1 completed. Final Test Accuracy: {test_acc:.2f}%")

writer.add_hparams(hparam_dict=hparams, metric_dict={'hparam/val_accuracy': best_val_acc, 'hparam/test_accuracy': test_acc}, run_name="hparams")
writer.close()
shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)

# ==========================================
# Run 2: Optimization and Background Regularization
# ==========================================
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm
import os
import shutil
from google.colab import drive

# 1. חיבור לדרייב ויצירת תיקיית גיבוי
print("מוודא חיבור ל-Google Drive...")
drive.mount('/content/drive')
BACKUP_DIR = '/content/drive/MyDrive/Trash_Classification_Project_Backup'
os.makedirs(BACKUP_DIR, exist_ok=True)
print(f"תיקיית הגיבוי מוכנה בנתיב: {BACKUP_DIR}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
run_name = "Run2_AdamW_Augs"
writer = SummaryWriter(f'runs/{run_name}')

hparams = {
    'img_size': 224,
    'batch_size': 32,
    'epochs': 80,
    'optimizer': 'AdamW',
    'learning_rate': 0.001,
    'weight_decay': 0.01,
    'augmentations': 'RandomResizedCrop, Flip, Rotate'
}

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_transforms = transforms.Compose([
    transforms.RandomResizedCrop(hparams['img_size'], scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    normalize
])

test_val_transforms = transforms.Compose([
    transforms.Resize((hparams['img_size'], hparams['img_size'])),
    transforms.ToTensor(),
    normalize
])

data_dir = "/content/split_dataset"
train_dataset = datasets.ImageFolder(os.path.join(data_dir, 'train'), transform=train_transforms)
val_dataset = datasets.ImageFolder(os.path.join(data_dir, 'val'), transform=test_val_transforms)
test_dataset = datasets.ImageFolder(os.path.join(data_dir, 'test'), transform=test_val_transforms)

train_loader = DataLoader(train_dataset, batch_size=hparams['batch_size'], shuffle=True, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size=hparams['batch_size'], shuffle=False, num_workers=4)
test_loader = DataLoader(test_dataset, batch_size=hparams['batch_size'], shuffle=False, num_workers=4)

model = models.resnet50(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(train_dataset.classes))
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=hparams['learning_rate'], weight_decay=hparams['weight_decay'])
best_val_acc = 0.0

for epoch in range(hparams['epochs']):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for inputs, labels in tqdm(train_loader, desc=f"Run 2 - Epoch {epoch+1}/{hparams['epochs']}"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    train_loss = running_loss / len(train_loader)
    train_acc = 100. * correct / total

    model.eval()
    val_loss, val_correct, val_total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            _, predicted = outputs.max(1)
            val_total += labels.size(0)
            val_correct += predicted.eq(labels).sum().item()

    val_loss = val_loss / len(val_loader)
    val_acc = 100. * val_correct / val_total
    print(f"Epoch {epoch+1}/{hparams['epochs']} - Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")
    writer.add_scalars('Loss', {'Train': train_loss, 'Val': val_loss}, epoch)
    writer.add_scalars('Accuracy', {'Train': train_acc, 'Val': val_acc}, epoch)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        save_path = os.path.join(BACKUP_DIR, f'{run_name}_best.pth')
        torch.save(model.state_dict(), save_path)

    shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)

model.load_state_dict(torch.load(os.path.join(BACKUP_DIR, f'{run_name}_best.pth')))
model.eval()
test_correct, test_total = 0, 0
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = outputs.max(1)
        test_total += labels.size(0)
        test_correct += predicted.eq(labels).sum().item()

test_acc = 100. * test_correct / test_total
print(f"Run 2 completed. Final Test Accuracy: {test_acc:.2f}%")

writer.add_hparams(hparam_dict=hparams, metric_dict={'hparam/val_accuracy': best_val_acc, 'hparam/test_accuracy': test_acc}, run_name="hparams")
writer.close()
shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)

# ==========================================
# Run 3: Ultimate Performance (AMP, Early Stopping, Checkpointing, Label Smoothing)
# ==========================================
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.tensorboard import SummaryWriter
import torch.cuda.amp as amp
from tqdm import tqdm
import os
import shutil
from google.colab import drive

# 1. חיבור לדרייב ויצירת תיקיית גיבוי
print("מוודא חיבור ל-Google Drive...")
drive.mount('/content/drive')
BACKUP_DIR = '/content/drive/MyDrive/Trash_Classification_Project_Backup'
os.makedirs(BACKUP_DIR, exist_ok=True)
print(f"תיקיית הגיבוי מוכנה בנתיב: {BACKUP_DIR}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
run_name = "Run3_Ultimate"
writer = SummaryWriter(f'runs/{run_name}')

hparams = {
    'img_size': 384,
    'batch_size': 128,
    'epochs': 150,
    'optimizer': 'AdamW',
    'learning_rate': 0.001,
    'weight_decay': 0.01,
    'augmentations': 'Advanced + AMP + Label Smoothing',
    'patience': 15
}

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

train_transforms = transforms.Compose([
    transforms.RandomResizedCrop(hparams['img_size'], scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(20),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    normalize
])

test_val_transforms = transforms.Compose([
    transforms.Resize((hparams['img_size'], hparams['img_size'])),
    transforms.ToTensor(),
    normalize
])

data_dir = "/content/split_dataset"
train_dataset = datasets.ImageFolder(os.path.join(data_dir, 'train'), transform=train_transforms)
val_dataset = datasets.ImageFolder(os.path.join(data_dir, 'val'), transform=test_val_transforms)
test_dataset = datasets.ImageFolder(os.path.join(data_dir, 'test'), transform=test_val_transforms)

train_loader = DataLoader(train_dataset, batch_size=hparams['batch_size'], shuffle=True, num_workers=4, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=hparams['batch_size'], shuffle=False, num_workers=4, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=hparams['batch_size'], shuffle=False, num_workers=4, pin_memory=True)

model = models.resnet50(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(train_dataset.classes))
model = model.to(device)

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = optim.AdamW(model.parameters(), lr=hparams['learning_rate'], weight_decay=hparams['weight_decay'])
scheduler = CosineAnnealingLR(optimizer, T_max=hparams['epochs'])
scaler = amp.GradScaler()

best_val_acc = 0.0
start_epoch = 0
epochs_no_improve = 0
checkpoint_path = os.path.join(BACKUP_DIR, f'{run_name}_checkpoint.pth')

if os.path.exists(checkpoint_path):
    print(f"Loading existing checkpoint from {checkpoint_path}...")
    checkpoint = torch.load(checkpoint_path)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
    start_epoch = checkpoint['epoch'] + 1
    best_val_acc = checkpoint['best_val_acc']
    print(f"Resuming training from epoch {start_epoch+1}")

for epoch in range(start_epoch, hparams['epochs']):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for inputs, labels in tqdm(train_loader, desc=f"Run 3 - Epoch {epoch+1}/{hparams['epochs']}"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()

        with amp.autocast():
            outputs = model(inputs)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    train_loss = running_loss / len(train_loader)
    train_acc = 100. * correct / total

    model.eval()
    val_loss, val_correct, val_total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            _, predicted = outputs.max(1)
            val_total += labels.size(0)
            val_correct += predicted.eq(labels).sum().item()

    val_loss = val_loss / len(val_loader)
    val_acc = 100. * val_correct / val_total
    print(f"Epoch {epoch+1}/{hparams['epochs']} - Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")
    scheduler.step()

    writer.add_scalars('Loss', {'Train': train_loss, 'Val': val_loss}, epoch)
    writer.add_scalars('Accuracy', {'Train': train_acc, 'Val': val_acc}, epoch)

    checkpoint = {
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'best_val_acc': best_val_acc
    }
    torch.save(checkpoint, checkpoint_path)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        epochs_no_improve = 0
        save_path = os.path.join(BACKUP_DIR, f'{run_name}_best.pth')
        torch.save(model.state_dict(), save_path)
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= hparams['patience']:
            print(f"Early stopping triggered after {epoch+1} epochs! No improvement in {hparams['patience']} epochs.")
            break

    shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)

model.load_state_dict(torch.load(os.path.join(BACKUP_DIR, f'{run_name}_best.pth')))
model.eval()
test_correct, test_total = 0, 0
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = outputs.max(1)
        test_total += labels.size(0)
        test_correct += predicted.eq(labels).sum().item()

test_acc = 100. * test_correct / test_total
print(f"Run 3 completed. Final Test Accuracy: {test_acc:.2f}%")

writer.add_hparams(
    hparam_dict=hparams,
    metric_dict={'hparam/val_accuracy': best_val_acc, 'hparam/test_accuracy': test_acc},
    run_name="hparams"
)
writer.close()
shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)

# ==========================================
# Run 4: ResNet18 (קטן יותר, מותאם לדאטא)
# ==========================================
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.tensorboard import SummaryWriter
import torch.cuda.amp as amp
from tqdm import tqdm
import os
import shutil
from google.colab import drive

# 1. חיבור לדרייב
print("מוודא חיבור ל-Google Drive...")
drive.mount('/content/drive')
BACKUP_DIR = '/content/drive/MyDrive/Trash_Classification_Project_Backup'
os.makedirs(BACKUP_DIR, exist_ok=True)
print(f"תיקיית הגיבוי מוכנה בנתיב: {BACKUP_DIR}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
run_name = "Run4_ResNet18"
writer = SummaryWriter(f'runs/{run_name}')

hparams = {
    'img_size': 224,
    'batch_size': 64,
    'epochs': 150,
    'optimizer': 'AdamW',
    'learning_rate': 0.001,
    'weight_decay': 0.01,
    'augmentations': 'Advanced + AMP + Label Smoothing',
    'patience': 15,
    'model': 'ResNet18'
}

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

train_transforms = transforms.Compose([
    transforms.RandomResizedCrop(hparams['img_size'], scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(20),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    normalize
])

test_val_transforms = transforms.Compose([
    transforms.Resize((hparams['img_size'], hparams['img_size'])),
    transforms.ToTensor(),
    normalize
])

data_dir = "/content/split_dataset"
train_dataset = datasets.ImageFolder(os.path.join(data_dir, 'train'), transform=train_transforms)
val_dataset   = datasets.ImageFolder(os.path.join(data_dir, 'val'),   transform=test_val_transforms)
test_dataset  = datasets.ImageFolder(os.path.join(data_dir, 'test'),  transform=test_val_transforms)

train_loader = DataLoader(train_dataset, batch_size=hparams['batch_size'], shuffle=True,  num_workers=4, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=hparams['batch_size'], shuffle=False, num_workers=4, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=hparams['batch_size'], shuffle=False, num_workers=4, pin_memory=True)

# ← השינוי המרכזי: ResNet18 במקום ResNet50
model = models.resnet18(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(train_dataset.classes))
model = model.to(device)

print(f"מספר פרמטרים: {sum(p.numel() for p in model.parameters()):,}")

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = optim.AdamW(model.parameters(), lr=hparams['learning_rate'], weight_decay=hparams['weight_decay'])
scheduler = CosineAnnealingLR(optimizer, T_max=hparams['epochs'])
scaler = amp.GradScaler()

best_val_acc = 0.0
start_epoch = 0
epochs_no_improve = 0
checkpoint_path = os.path.join(BACKUP_DIR, f'{run_name}_checkpoint.pth')

if os.path.exists(checkpoint_path):
    print(f"טוען checkpoint מ-{checkpoint_path}...")
    checkpoint = torch.load(checkpoint_path)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
    start_epoch = checkpoint['epoch'] + 1
    best_val_acc = checkpoint['best_val_acc']
    epochs_no_improve = checkpoint['epochs_no_improve']  # ← תיקון: נשמר ב-checkpoint
    print(f"ממשיך אימון מ-epoch {start_epoch + 1} | best val acc: {best_val_acc:.2f}%")

for epoch in range(start_epoch, hparams['epochs']):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for inputs, labels in tqdm(train_loader, desc=f"Run 4 - Epoch {epoch+1}/{hparams['epochs']}"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()

        with torch.amp.autocast('cuda'):  # ← תיקון: ללא FutureWarning
            outputs = model(inputs)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    train_loss = running_loss / len(train_loader)
    train_acc  = 100. * correct / total

    model.eval()
    val_loss, val_correct, val_total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            _, predicted = outputs.max(1)
            val_total += labels.size(0)
            val_correct += predicted.eq(labels).sum().item()

    val_loss = val_loss / len(val_loader)
    val_acc  = 100. * val_correct / val_total
    scheduler.step()

    print(f"Epoch {epoch+1}/{hparams['epochs']} - Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")

    writer.add_scalars('Loss',     {'Train': train_loss, 'Val': val_loss}, epoch)
    writer.add_scalars('Accuracy', {'Train': train_acc,  'Val': val_acc},  epoch)

    # שמירת checkpoint – כולל epochs_no_improve
    checkpoint = {
        'epoch':                epoch,
        'model_state_dict':     model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'best_val_acc':         best_val_acc,
        'epochs_no_improve':    epochs_no_improve  # ← תיקון
    }
    torch.save(checkpoint, checkpoint_path)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        epochs_no_improve = 0
        save_path = os.path.join(BACKUP_DIR, f'{run_name}_best.pth')
        torch.save(model.state_dict(), save_path)
        print(f"  → מודל חדש נשמר! Val Acc: {val_acc:.2f}%")
        shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)  # ← תיקון: רק כשיש שיפור
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= hparams['patience']:
            print(f"Early stopping לאחר {epoch+1} epochs – אין שיפור במשך {hparams['patience']} epochs.")
            break

# הערכה על test set
model.load_state_dict(torch.load(os.path.join(BACKUP_DIR, f'{run_name}_best.pth')))
model.eval()
test_correct, test_total = 0, 0
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = outputs.max(1)
        test_total += labels.size(0)
        test_correct += predicted.eq(labels).sum().item()

test_acc = 100. * test_correct / test_total
print(f"\nRun 4 הסתיים. Test Accuracy: {test_acc:.2f}% | Best Val Accuracy: {best_val_acc:.2f}%")

writer.add_hparams(
    hparam_dict=hparams,
    metric_dict={'hparam/val_accuracy': best_val_acc, 'hparam/test_accuracy': test_acc},
    run_name="hparams"
)
writer.close()
shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)

# ==========================================
# Run 5: ResNet18 + Augmentations חזקות (RandomErasing + MixUp)
# ==========================================
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm
import os
import shutil
from google.colab import drive

# 1. חיבור לדרייב
print("מוודא חיבור ל-Google Drive...")
drive.mount('/content/drive')
BACKUP_DIR = '/content/drive/MyDrive/Trash_Classification_Project_Backup'
os.makedirs(BACKUP_DIR, exist_ok=True)
print(f"תיקיית הגיבוי מוכנה בנתיב: {BACKUP_DIR}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
run_name = "Run5_ResNet18_Augs"
writer = SummaryWriter(f'runs/{run_name}')

hparams = {
    'img_size': 224,
    'batch_size': 64,
    'epochs': 150,
    'optimizer': 'AdamW',
    'learning_rate': 0.001,
    'weight_decay': 0.01,
    'augmentations': 'RandomErasing + MixUp',
    'patience': 15,
    'model': 'ResNet18',
    'mixup_alpha': 0.2,
    'erasing_prob': 0.3
}

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])

train_transforms = transforms.Compose([
    transforms.RandomResizedCrop(hparams['img_size'], scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(20),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    normalize,
    # ← חדש: מסתיר אזורים אקראיים בתמונה
    transforms.RandomErasing(p=hparams['erasing_prob'], scale=(0.02, 0.2))
])

test_val_transforms = transforms.Compose([
    transforms.Resize((hparams['img_size'], hparams['img_size'])),
    transforms.ToTensor(),
    normalize
])

data_dir = "/content/split_dataset"
train_dataset = datasets.ImageFolder(os.path.join(data_dir, 'train'), transform=train_transforms)
val_dataset   = datasets.ImageFolder(os.path.join(data_dir, 'val'),   transform=test_val_transforms)
test_dataset  = datasets.ImageFolder(os.path.join(data_dir, 'test'),  transform=test_val_transforms)

train_loader = DataLoader(train_dataset, batch_size=hparams['batch_size'], shuffle=True,  num_workers=4, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=hparams['batch_size'], shuffle=False, num_workers=4, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=hparams['batch_size'], shuffle=False, num_workers=4, pin_memory=True)


# ← פונקציית MixUp: מערבבת שתי תמונות ו-labels
def mixup_batch(inputs, labels, alpha=0.2):
    lam = np.random.beta(alpha, alpha)
    batch_size = inputs.size(0)
    index = torch.randperm(batch_size).to(device)
    mixed_inputs = lam * inputs + (1 - lam) * inputs[index]
    labels_a, labels_b = labels, labels[index]
    return mixed_inputs, labels_a, labels_b, lam

def mixup_criterion(criterion, outputs, labels_a, labels_b, lam):
    return lam * criterion(outputs, labels_a) + (1 - lam) * criterion(outputs, labels_b)


model = models.resnet18(weights=None)
model.fc = nn.Linear(model.fc.in_features, len(train_dataset.classes))
model = model.to(device)

print(f"מספר פרמטרים: {sum(p.numel() for p in model.parameters()):,}")

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = optim.AdamW(model.parameters(), lr=hparams['learning_rate'], weight_decay=hparams['weight_decay'])
scheduler = CosineAnnealingLR(optimizer, T_max=hparams['epochs'])
scaler = torch.amp.GradScaler('cuda')

best_val_acc = 0.0
start_epoch = 0
epochs_no_improve = 0
checkpoint_path = os.path.join(BACKUP_DIR, f'{run_name}_checkpoint.pth')

if os.path.exists(checkpoint_path):
    print(f"טוען checkpoint מ-{checkpoint_path}...")
    checkpoint = torch.load(checkpoint_path)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
    start_epoch = checkpoint['epoch'] + 1
    best_val_acc = checkpoint['best_val_acc']
    epochs_no_improve = checkpoint['epochs_no_improve']
    print(f"ממשיך אימון מ-epoch {start_epoch + 1} | best val acc: {best_val_acc:.2f}%")

for epoch in range(start_epoch, hparams['epochs']):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for inputs, labels in tqdm(train_loader, desc=f"Run 5 - Epoch {epoch+1}/{hparams['epochs']}"):
        inputs, labels = inputs.to(device), labels.to(device)

        # ← MixUp על כל batch
        inputs, labels_a, labels_b, lam = mixup_batch(inputs, labels, alpha=hparams['mixup_alpha'])

        optimizer.zero_grad()
        with torch.amp.autocast('cuda'):
            outputs = model(inputs)
            loss = mixup_criterion(criterion, outputs, labels_a, labels_b, lam)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels_a.size(0)
        # accuracy מחושב לפי labels_a (הלייבל הראשי)
        correct += (lam * predicted.eq(labels_a).sum().item()
                    + (1 - lam) * predicted.eq(labels_b).sum().item())

    train_loss = running_loss / len(train_loader)
    train_acc  = 100. * correct / total

    # Validation – ללא MixUp
    model.eval()
    val_loss, val_correct, val_total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            _, predicted = outputs.max(1)
            val_total += labels.size(0)
            val_correct += predicted.eq(labels).sum().item()

    val_loss = val_loss / len(val_loader)
    val_acc  = 100. * val_correct / val_total
    scheduler.step()

    print(f"Epoch {epoch+1}/{hparams['epochs']} - Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")

    writer.add_scalars('Loss',     {'Train': train_loss, 'Val': val_loss}, epoch)
    writer.add_scalars('Accuracy', {'Train': train_acc,  'Val': val_acc},  epoch)

    checkpoint = {
        'epoch':                epoch,
        'model_state_dict':     model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'best_val_acc':         best_val_acc,
        'epochs_no_improve':    epochs_no_improve
    }
    torch.save(checkpoint, checkpoint_path)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        epochs_no_improve = 0
        save_path = os.path.join(BACKUP_DIR, f'{run_name}_best.pth')
        torch.save(model.state_dict(), save_path)
        print(f"  → מודל חדש נשמר! Val Acc: {val_acc:.2f}%")
        shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= hparams['patience']:
            print(f"Early stopping לאחר {epoch+1} epochs – אין שיפור במשך {hparams['patience']} epochs.")
            break

# הערכה על test set
model.load_state_dict(torch.load(os.path.join(BACKUP_DIR, f'{run_name}_best.pth')))
model.eval()
test_correct, test_total = 0, 0
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = outputs.max(1)
        test_total += labels.size(0)
        test_correct += predicted.eq(labels).sum().item()

test_acc = 100. * test_correct / test_total
print(f"\nRun 5 הסתיים. Test Accuracy: {test_acc:.2f}% | Best Val Accuracy: {best_val_acc:.2f}%")

writer.add_hparams(
    hparam_dict=hparams,
    metric_dict={'hparam/val_accuracy': best_val_acc, 'hparam/test_accuracy': test_acc},
    run_name="hparams"
)
writer.close()
shutil.copytree('runs', os.path.join(BACKUP_DIR, 'runs'), dirs_exist_ok=True)

# ==========================================
# Post-Analysis: גרפים וטבלאות לספר הפרויקט
# ==========================================
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
from sklearn.preprocessing import label_binarize
import os

# ודא שהנתיבים תואמים למה שהגדרת קודם
BACKUP_DIR = '/content/drive/MyDrive/Trash_Classification_Project_Backup'
# בחר את המודל שאתה רוצה לנתח (נניח Run4 או Run5)
BEST_MODEL_PATH = os.path.join(BACKUP_DIR, 'Run4_ResNet18_best.pth')

# יצירת תיקייה ייעודית לשמירת הגרפים בדרייב
GRAPHS_DIR = os.path.join(BACKUP_DIR, 'Final_Graphs')
os.makedirs(GRAPHS_DIR, exist_ok=True)

print("טוען את המודל לניתוח...")
model.load_state_dict(torch.load(BEST_MODEL_PATH))
model.eval()

# איסוף הנתונים מסט המבחן
all_preds = []
all_labels = []
all_probs = []

print("מריץ את המודל על סט המבחן...")
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        probs = torch.nn.functional.softmax(outputs, dim=1)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs.cpu().numpy())

all_preds = np.array(all_preds)
all_labels = np.array(all_labels)
all_probs = np.array(all_probs)
class_names = test_dataset.classes

# ---------------------------------------------------------
# 1. מטריצת בלבול (Confusion Matrix)
# ---------------------------------------------------------
print("מייצר מטריצת בלבול...")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix - Test Set')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
cm_path = os.path.join(GRAPHS_DIR, 'confusion_matrix.png')
plt.savefig(cm_path, dpi=300)
plt.show()

# ---------------------------------------------------------
# 2. דוח סיווג (Classification Report)
# ---------------------------------------------------------
print("\n" + "="*50)
print("CLASSIFICATION REPORT")
print("="*50)
report = classification_report(all_labels, all_preds, target_names=class_names)
print(report)
# שמירת הדוח לקובץ טקסט
with open(os.path.join(GRAPHS_DIR, 'classification_report.txt'), 'w') as f:
    f.write(report)

# ---------------------------------------------------------
# 3. עקומות ROC ו-AUC לכל מחלקה
# ---------------------------------------------------------
print("\nמייצר עקומות ROC...")
# בינאריזציה של התיוגים עבור ROC
y_test_bin = label_binarize(all_labels, classes=range(len(class_names)))
n_classes = y_test_bin.shape[1]

fpr = dict()
tpr = dict()
roc_auc = dict()

plt.figure(figsize=(10, 8))
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], all_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])
    plt.plot(fpr[i], tpr[i], lw=2, label=f'{class_names[i]} (AUC = {roc_auc[i]:.3f})')

plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.tight_layout()
roc_path = os.path.join(GRAPHS_DIR, 'roc_curves.png')
plt.savefig(roc_path, dpi=300)
plt.show()

# ---------------------------------------------------------
# 4. תצוגת חיזוי חזותית (Visual Predictions Grid)
# ---------------------------------------------------------
print("מייצר תצוגת רשת (Grid) של תחזיות...")
def imshow(inp, title=None, color='black'):
    """Imshow for Tensor."""
    inp = inp.numpy().transpose((1, 2, 0))
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    inp = std * inp + mean
    inp = np.clip(inp, 0, 1)
    plt.imshow(inp)
    if title is not None:
        plt.title(title, color=color, fontsize=12, fontweight='bold')
    plt.axis('off')

# לקיחת באצ' אחד אקראי מסט המבחן
inputs, labels = next(iter(test_loader))
inputs, labels = inputs.to(device), labels.to(device)
outputs = model(inputs)
_, preds = torch.max(outputs, 1)

fig = plt.figure(figsize=(15, 15))
# נציג 16 תמונות אקראיות
for i in range(min(16, inputs.size(0))):
    ax = fig.add_subplot(4, 4, i+1)
    correct = preds[i] == labels[i]
    color = 'green' if correct else 'red'
    title = f"Pred: {class_names[preds[i]]}\nTrue: {class_names[labels[i]]}"
    imshow(inputs.cpu()[i], title, color)

plt.tight_layout()
grid_path = os.path.join(GRAPHS_DIR, 'prediction_grid.png')
plt.savefig(grid_path, dpi=300)
plt.show()

print(f"\n✅ כל הגרפים ודוח הסיווג נשמרו בדרייב שלך בתיקייה:\n{GRAPHS_DIR}")

# ==========================================
# Post-Analysis עבור הרצה 5 (MixUp + Random Erasing)
# ==========================================
import torch
import torch.nn as nn
from torchvision import models
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
from sklearn.preprocessing import label_binarize
import os

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BACKUP_DIR = '/content/drive/MyDrive/Trash_Classification_Project_Backup'

# 1. הנתיב למודל של הרצה 5
BEST_MODEL_PATH = os.path.join(BACKUP_DIR, 'Run5_ResNet18_Augs_best.pth')

# 2. תיקייה נפרדת להרצה 5 כדי לא לדרוס את הרצה 4
GRAPHS_DIR = os.path.join(BACKUP_DIR, 'Final_Graphs_Run5')
os.makedirs(GRAPHS_DIR, exist_ok=True)

# מוודאים שהמודל מוגדר כ-ResNet18 לפני הטעינה
print("מכין את ארכיטקטורת המודל...")
model_eval = models.resnet18(weights=None)
model_eval.fc = nn.Linear(model_eval.fc.in_features, len(test_dataset.classes))
model_eval = model_eval.to(device)

print(f"טוען את המשקלים מ:\n{BEST_MODEL_PATH}")
model_eval.load_state_dict(torch.load(BEST_MODEL_PATH))
model_eval.eval()

all_preds = []
all_labels = []
all_probs = []

print("מריץ את המודל המנצח של הרצה 5 על סט המבחן...")
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model_eval(inputs)
        probs = torch.nn.functional.softmax(outputs, dim=1)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs.cpu().numpy())

all_preds = np.array(all_preds)
all_labels = np.array(all_labels)
all_probs = np.array(all_probs)
class_names = test_dataset.classes

# ---------------------------------------------------------
# 1. מטריצת בלבול (Confusion Matrix)
# ---------------------------------------------------------
print("מייצר מטריצת בלבול...")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Oranges', xticklabels=class_names, yticklabels=class_names) # שמתי צבע כתום כדי שתבדיל מהרצה 4
plt.title('Confusion Matrix - Run 5 (Test Set)')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
cm_path = os.path.join(GRAPHS_DIR, 'confusion_matrix_run5.png')
plt.savefig(cm_path, dpi=300)
plt.show()

# ---------------------------------------------------------
# 2. דוח סיווג (Classification Report)
# ---------------------------------------------------------
print("\n" + "="*50)
print("CLASSIFICATION REPORT - RUN 5")
print("="*50)
report = classification_report(all_labels, all_preds, target_names=class_names)
print(report)
with open(os.path.join(GRAPHS_DIR, 'classification_report_run5.txt'), 'w') as f:
    f.write(report)

# ---------------------------------------------------------
# 3. עקומות ROC ו-AUC
# ---------------------------------------------------------
print("\nמייצר עקומות ROC...")
y_test_bin = label_binarize(all_labels, classes=range(len(class_names)))
n_classes = y_test_bin.shape[1]

fpr = dict()
tpr = dict()
roc_auc = dict()

plt.figure(figsize=(10, 8))
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], all_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])
    plt.plot(fpr[i], tpr[i], lw=2, label=f'{class_names[i]} (AUC = {roc_auc[i]:.3f})')

plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Run 5')
plt.legend(loc="lower right")
plt.tight_layout()
roc_path = os.path.join(GRAPHS_DIR, 'roc_curves_run5.png')
plt.savefig(roc_path, dpi=300)
plt.show()

# ---------------------------------------------------------
# 4. תצוגת חיזוי חזותית (Visual Predictions Grid)
# ---------------------------------------------------------
print("מייצר תצוגת רשת (Grid) של תחזיות...")
def imshow(inp, title=None, color='black'):
    inp = inp.numpy().transpose((1, 2, 0))
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    inp = std * inp + mean
    inp = np.clip(inp, 0, 1)
    plt.imshow(inp)
    if title is not None:
        plt.title(title, color=color, fontsize=12, fontweight='bold')
    plt.axis('off')

inputs, labels = next(iter(test_loader))
inputs, labels = inputs.to(device), labels.to(device)
outputs = model_eval(inputs)
_, preds = torch.max(outputs, 1)

fig = plt.figure(figsize=(15, 15))
for i in range(min(16, inputs.size(0))):
    ax = fig.add_subplot(4, 4, i+1)
    correct = preds[i] == labels[i]
    color = 'green' if correct else 'red'
    title = f"Pred: {class_names[preds[i]]}\nTrue: {class_names[labels[i]]}"
    imshow(inputs.cpu()[i], title, color)

plt.tight_layout()
grid_path = os.path.join(GRAPHS_DIR, 'prediction_grid_run5.png')
plt.savefig(grid_path, dpi=300)
plt.show()

print(f"\n✅ כל הגרפים ודוח הסיווג של הרצה 5 נשמרו בדרייב שלך בתיקייה:\n{GRAPHS_DIR}")